import Head from 'next/head'
import { Inter } from '@next/font/google'
import Signup from './signup'
import Login from './login';
const finnhub = require('finnhub');
import Link from 'next/link'
import { useAuth } from '@/context/AuthContext';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {user} = useAuth()
  //const finnhub = require('finnhub');

  // const api_key = finnhub.ApiClient.instance.authentications['api_key'];
  // api_key.apiKey = "cfd98fpr01qj357esqt0cfd98fpr01qj357esqtg"
  // const finnhubClient = new finnhub.DefaultApi()

  // finnhubClient.stockCandles("AAPL", "D", 1590988249, 1591852249, (error, data, response) => {
  //   console.log(data)
  // });

  return (
    <>
      <Head>
        <title>Shopr Assignment</title>
        <meta name="description" content="Shopr Assignment Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
          {user ? <Login/> : <Signup/>}
      </main>
    </>
  )
}
