import Head from 'next/head'
import { Inter } from '@next/font/google'
import Signup from './signup'
import Login from './login';
import Link from 'next/link'
import { useAuth } from '@/context/AuthContext';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {user} = useAuth()
  

  return (
    <>
      <Head>
        <title>Shopr Assignment</title>
        <meta name="description" content="Shopr Assignment Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
          {user ? <Login/> : <Signup/>}
      </main>
    </>
  )
}
